server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://103.200.23.126:3306/hiepvhdb_identityDB"
    username: hiepvhdb_hiep
    password: Zmxncbv2002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jwt:
    signerKey: "L1wfHX6Xmk3/S0CACCsYXVg0UGRhNjvtnh8ntOgKPrFX3BBKvJ23pFMSTkjcAgm/"
