spring.application.name=hospital

server.port=8080
#spring.datasource.url=jdbc:postgresql://35.247.175.13:5432/hospital
#spring.datasource.username=postgres
#spring.datasource.password=example
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=123456


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true